/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsIndexRouteImport } from './routes/forms/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ResponsesFormIdRouteImport } from './routes/responses/$formId'
import { Route as FormsNewRouteImport } from './routes/forms/new'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as QuizFormIdResultsRouteImport } from './routes/quiz/$formId/results'
import { Route as FormsFormIdTakeRouteImport } from './routes/forms/$formId/take'
import { Route as FormsFormIdEditRouteImport } from './routes/forms/$formId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsesFormIdRoute = ResponsesFormIdRouteImport.update({
  id: '/responses/$formId',
  path: '/responses/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizFormIdResultsRoute = QuizFormIdResultsRouteImport.update({
  id: '/quiz/$formId/results',
  path: '/quiz/$formId/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdTakeRoute = FormsFormIdTakeRouteImport.update({
  id: '/forms/$formId/take',
  path: '/forms/$formId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdEditRoute = FormsFormIdEditRouteImport.update({
  id: '/forms/$formId/edit',
  path: '/forms/$formId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/forms/new': typeof FormsNewRoute
  '/responses/$formId': typeof ResponsesFormIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/forms': typeof FormsIndexRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/take': typeof FormsFormIdTakeRoute
  '/quiz/$formId/results': typeof QuizFormIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/forms/new': typeof FormsNewRoute
  '/responses/$formId': typeof ResponsesFormIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/forms': typeof FormsIndexRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/take': typeof FormsFormIdTakeRoute
  '/quiz/$formId/results': typeof QuizFormIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/forms/new': typeof FormsNewRoute
  '/responses/$formId': typeof ResponsesFormIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/take': typeof FormsFormIdTakeRoute
  '/quiz/$formId/results': typeof QuizFormIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/forms/new'
    | '/responses/$formId'
    | '/dashboard'
    | '/forms'
    | '/forms/$formId/edit'
    | '/forms/$formId/take'
    | '/quiz/$formId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/forms/new'
    | '/responses/$formId'
    | '/dashboard'
    | '/forms'
    | '/forms/$formId/edit'
    | '/forms/$formId/take'
    | '/quiz/$formId/results'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/forms/new'
    | '/responses/$formId'
    | '/dashboard/'
    | '/forms/'
    | '/forms/$formId/edit'
    | '/forms/$formId/take'
    | '/quiz/$formId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  FormsNewRoute: typeof FormsNewRoute
  ResponsesFormIdRoute: typeof ResponsesFormIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FormsIndexRoute: typeof FormsIndexRoute
  FormsFormIdEditRoute: typeof FormsFormIdEditRoute
  FormsFormIdTakeRoute: typeof FormsFormIdTakeRoute
  QuizFormIdResultsRoute: typeof QuizFormIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/': {
      id: '/forms/'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responses/$formId': {
      id: '/responses/$formId'
      path: '/responses/$formId'
      fullPath: '/responses/$formId'
      preLoaderRoute: typeof ResponsesFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$formId/results': {
      id: '/quiz/$formId/results'
      path: '/quiz/$formId/results'
      fullPath: '/quiz/$formId/results'
      preLoaderRoute: typeof QuizFormIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/take': {
      id: '/forms/$formId/take'
      path: '/forms/$formId/take'
      fullPath: '/forms/$formId/take'
      preLoaderRoute: typeof FormsFormIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/edit': {
      id: '/forms/$formId/edit'
      path: '/forms/$formId/edit'
      fullPath: '/forms/$formId/edit'
      preLoaderRoute: typeof FormsFormIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  FormsNewRoute: FormsNewRoute,
  ResponsesFormIdRoute: ResponsesFormIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FormsIndexRoute: FormsIndexRoute,
  FormsFormIdEditRoute: FormsFormIdEditRoute,
  FormsFormIdTakeRoute: FormsFormIdTakeRoute,
  QuizFormIdResultsRoute: QuizFormIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
